### ISSUE TITLE
Trouble Shooting cron: `Undefined index: REQUEST_URI`

### ISSUE THREAD

**Issue by ShawnPConroy** [liuch/dmarc-srg#139]
Good day,

Deploying on a cPanel shared host account required me to overcome #136 and #138 and everything was working. I went to setup a production copy by downloading the the tar.gz file, extracting it, and editing the config, and using the SQL I had already setup.

It works via command line. It works via the web. For the cron I commented out the `exit()` that requires the sapi to be `cli`. However, I get this strange error and now cannot get any copy to work via cron, despite it all working this morning before I tried to get a fresh install going.

```
dmarc-srg [error]: ErrorException: Undefined index: REQUEST_URI in [...]/dmarc-srg/classes/Core.php:401
Stack trace:
#0 [...]/classes/Core.php(401): {closure}(8, 'Undefined index...', '/home/[...]/...', 401, Array)
#1 [...]/classes/Core.php(107): Liuch\DmarcSrg\Core::startSession()
#2 [...]/utils/summary_report.php(129): Liuch\DmarcSrg\Core->user('admin')
#3 {main}
```

This happens with `fetch_reports.php` and `summary_report.php`.

**Comment by liuch** [comment]
Thank you for the report. Fixed.
