### ISSUE TITLE
Feature request - resolve IPs to DNS names

### ISSUE THREAD

**Issue by williamdes** [liuch/dmarc-srg#75]
There is two things I did find frustrating when reading reports today:
- When I click on the IP link all the information is useless to me as I would have needed
   - It's reverse DNS name
   - What MX records exist for this reversed DNS name
- reverse DNS support when displaying an IP, since an IP is not very informative when browsing my clients reports
I need to have a visual way to find out what service is behind the IP in the report without having to open a ton of tabs

So what about reverse DNS support ?

**Comment by liuch** [comment]
> When I click on the IP link all the information is useless to me as I would have needed

FYI: You can set up another service to display this information.

I need to think how and where to accurately display this information. BTW: there is already a suitable pull request: https://github.com/liuch/dmarc-srg/pull/5

**Comment by KlaasBonnema** [comment]
I made some changes that will do a hostname lookup on server IP and then validate that a reverse lookup for ip-address using the hostname returns the original ip-address. A failing lookup of ip-address match will mark the ip-address - hostname entry as red while a match will mark the entry as green. This is similar to the ip-rev check that mail receivers will perform to spot improper mail senders.
The actual lookup is being performed by a PHP script. It is called in parallel by an asynchronous fetch so that the dns lookups are executed also in parallel and will not adversly impact page load times.

common.js
```js
	static makeIpElement(ip) {
		let url = null;
		let type = ip.includes(":") && 6 || 4;
		switch (type) {
			case 4:
				url = Common.ipv4_url;
				break;
			case 6:
				url = Common.ipv6_url;
				break;
		}
		let tn = document.createTextNode(ip);
		if (url) {
			url = url.replace("{$ip}", ip).replace("{$eip}", encodeURIComponent(ip));
			let el = document.createElement("a");
			el.setAttribute("href", url);
			el.setAttribute("target", "_blank");
			el.setAttribute("title", "IP address - hostname");
			el.appendChild(tn);
			this.resolveIp(ip, type)
				.then((response) => {
					el.setAttribute("class", 'ip-address');
					el.innerHTML = el.innerHTML + " - " + response.hostname;
					if (response.status == 'valid')
						el.setAttribute("class", 'report-result-pass');
					else
						el.setAttribute("class", 'report-result-fail');
				})
				.catch(console.log);
			return el;
		}
		else {
			this.resolveIp(ip, type)
				.then((response) => {
					tn.textContent = tn.textContent + " - " + response.hostname;
					if (response.status == 'valid')
						tn.parentNode.setAttribute("class", 'report-result-pass');
					else
						tn.parentNode.setAttribute("class", 'report-result-fail');
				})
				.catch(console.log);
		}
		return tn;
	}

	static resolveIp = async (ip, type) => {
		const response = await fetch("resolve_ip.php?ip=" + ip + "&type=" + type);
		if (response.ok) {
			return response.json();
		}
	};
```js

resolve_ip.php
```php
<?php
/**
 * Resolve ip-address to hostname and perform reverse lookup to match resolved hostname with ip-address.
 * Mail servers should be set up in dns with a dedicated static hostname. 
 * Flag invalid and non-matching ip-address - hostname pairs.  
 * @var string $ip
 */
$response = array();
$ip = $_GET['ip'];
$type = $_GET['type'];

// empty $ip parameter is invalid
if (empty($ip))
{
    $response['status'] = "invalid";
    $response['hostname'] = "hostname lookup invalid";
    echo json_encode($response);
    exit();
}

// get the hostname by ip
$hostname = gethostbyaddr($ip);
if ($hostname === false)
{
    $response['status'] = "invalid";
    $response['hostname'] = "hostname lookup failed";
    echo json_encode($response);
    exit();
}

// lookup dns to get an array of ip_addresses by hostname
switch ($type)
{
    case "6":
        {
            // lookup ipv6 
            $ip_res = dns_get_record($hostname, DNS_AAAA);
            break;
        }
    case "4":
    default:
        {
            // lookup ipv4
            $ip_res = dns_get_record($hostname, DNS_A);
            break;
        }
}

// invalid if result is not an array
if (! is_array($ip_res))
{
    $response['status'] = "invalid";
    $response['hostname'] = $hostname;
    echo json_encode($response);
    exit();
}

// match our input ip with the result ip's. A match returns a valid status
foreach ($ip_res as $entry)
{
    if (($type == "6" && isset($entry['ipv6']) && inet_ntop(inet_pton($entry['ipv6'])) == $ip) || (isset($entry['ip']) && $entry['ip'] == $ip))
    {
        $response['status'] = "valid";
        $response['hostname'] = $hostname;
        echo json_encode($response);
        exit();
    }
}

// no match found, return invalid status
$response['status'] = "invalid";
$response['hostname'] = $hostname;
echo json_encode($response);
exit();
```

**Comment by liuch** [comment]
I will try to implement something like this. At the very least, your php code lacks input parameter validation and access level validation. There are questions to the js code as well. But the main thing is your idea. Thank you.

**Comment by williamdes** [comment]
https://github.com/domainaware/parsedmarc/blob/8.17.0/parsedmarc/resources/maps/base_reverse_dns_map.csv

To map domains to ISP names

**Comment by liuch** [comment]
> What MX records exist for this reversed DNS name

Probably not one. The hostname will most likely contain the domain name, but does not have to be identical to the domain. If configured correctly, it must not match. For example, gmail email hosts don't even always have the domain part matching.

In a recent email with a sender on the gmail server, from the Received header I took this IP address: 209.85.220.41  
Checking:

``` sh
$ host 209.85.220.41
41.220.85.209.in-addr.arpa domain name pointer mail-sor-f41.google.com.

$ dig +short mx mail-sor-f41.google.com
$
```
Nothing.

Worse, if you try to get the IP address from the received host, it won't match the address from the email:

``` sh
$ dig +short mail-sor-f41.google.com
209.85.220.41
```
Perhaps I misunderstood something and you meant a different check. Could you please share your thoughts?

**Comment by KlaasBonnema** [comment]
I am running with my suggested code for several month's now. It will do a dynamic reverse lookup to get the dns name and then a dns name to ip lookup to verify it matches the original ip-address. Essentially this is the ip-rev check that mail servers perform.
The code displays the dns name together with the ip-address in summary reports and incomming record reports. If the ip-rev check fails the name will be in red.
This gives me a quick view of the mail server that processed the request. 

In practice you will see many names matching your own mail provider's servers. They will probably look something like mo4-p00-ob.smtp.provider.com where the "provider.com" part is identical. The vast majority of servernames will be from a very small number of providers.

A better way to do this is to perform the ip-rev check when processing the incomming reports. Before the ip-rev check, lookup the ip-address in a database table of previously found adresses where you store the full dns name. This will further avoid the overhead of doing the ip-rev checks.
Then allow the user to configure an alias name for addresses matching a common "provider.com" part.

In the summary report you can create an option to group all servers matching a common "provider.com" together. Servernames that were not yet assigned to a common provider name will stick out, which is what you want to spot exceptions.
In incomming records you would display ip-address, full dns name and the common provider name alias.

A further enhancement could be to collect mx records. Question then is how you would detect a change in mx configurations.

Using a big provider list cannot be maintained. The list provided by Williamdes does not contain any of the providers that I commonly see.

**Comment by liuch** [comment]
@KlaasBonnema, thank you for your reply. Unfortunately, the method you described does not work for every configuration. The host that sends mail and the host that receives mail may be in different domains. IP addresses in the result of gethostbyaddr -> dns_get_record may not match.

A little later I will add the hosts table to the database, but now I'm trying to figure out what host information will be most useful in the Web UI report view dialog.

**Comment by KlaasBonnema** [comment]
"The host that sends mail and the host that receives mail may be in different domains. IP addresses in the result of gethostbyaddr -> dns_get_record may not match."

Do you mean that you may not be able to resolve the smtp server ip_address reported by dmarc because it is not accessable by the server that runs dmarc-srg (behind a firewall)? Dmarc-srg unable to do dns resolve requests would indeed block any informational lookup.

The smtp server itself behind a firewall is unlikely because it would not be able to do its job.

In recent reports I have two ip_addresses that did not pass the ip-rev test. One has a japanese domain name but no matching ip-address. The other does not even resolve to a domain name. Both requests were dmarc rejected. It is easy to identify these two attempts as illegal use of our domain for sending e-mail using a faked ip_address.
The other hundreds of smtp server ip-addresses can be grouped in no more than a dozen provider domains.

**Comment by liuch** [comment]
I apologize, I seem to be confused myself in my experiments with rDNS. I guess I need to write tests and check my conclusions on more reports.

**Comment by liuch** [comment]
As for the summary report - I haven't figured out how to do it properly and safely yet.

**Comment by williamdes** [comment]
This looks really nice !

> rDNS and Reverse IP are cached for 24 hours for the current browser tab. Caching on the server is not implemented yet. Ideally, these requests should be cached by DNS resolver installed on the server.

Can you make the code in order to allow a community plugin to be added for the resolving process ?
I guess such a plugin could enrich the data shown in the modal. But also do the same work but with server side caching or fetch from another source than DNS

A class that can be extended could work, I am not sure. Do what is best for you :)

**Comment by liuch** [comment]
@williamdes I thank you for your appreciation of this functionality. As for the plugin manager: I like the idea, but the problem is that I have no idea yet how it should be implemented. The ones I googled in a few minutes I didn't like. I am going to familiarize myself with this subject more deeply in the near future.

**Comment by liuch** [comment]
> Can you make the code in order to allow a community plugin to be added for the resolving process ?

Implemented with https://github.com/liuch/dmarc-srg/commit/d0ef3222af09d3615eed08fefe8aadb039f36804

**Comment by williamdes** [comment]
Very nice, maybe use https://www.php.net/manual/en/function.class-implements.php instead of new and checking

**Comment by williamdes** [comment]
> Honestly right now I don't see the advantage of using the class_implements function. To get rid of most of the checks in PluginManager I will have to write an autoloader that takes into account the structure of the plugins directory. Nevertheless, I agree with you: the plugin loading code looks clumsy. I should definitely refactor it.

When I first read the new code a bug finding did spawn in my mind: What is the construct of this class is incompatible and is not a plugin ?
it will break everything. But that's only a theory
Also: The hooks methods to implement do not seems forced by an interface, maybe one more could be added for each group of hooks ?

**Comment by liuch** [comment]
> What is the construct of this class is incompatible and is not a plugin ?

Autoloader cannot guarantee absence of such errors either.

> Also: The hooks methods to implement do not seems forced by an interface, maybe one more could be added for each group of hooks ?

In this case, a plugin will have to implement methods for each event, even if this plugin handles only one of them. Or use one separate interface for each event, that seems redundant to me.

**Comment by ReVoLt112** [comment]
> I have currently implemented this functionality as follows:
> 
> ![Host information](https://github.com/user-attachments/assets/9b4751e9-c452-499d-a439-97ac62ba9343)
> 
> 1. IP address
> 2. rDNS name for this IP
> 3. Reverse IP (match / not match)
> 4. Total reports for this IP address (all domains available to the user)
> 5. Total messages for this IP address (all domains available to the user)
> 6. Last report containing this IP address excluding the current report, if possible (all domains...)
> 
> A request to the server is sent only when the corresponding button is pressed. This is implemented so as not to overload the server with numerous requests if there are many records in the report. Perhaps later requests to the server will be sent as the report page scrolls or something.
> 
> rDNS and Reverse IP are cached for 24 hours for the current browser tab. Caching on the server is not implemented yet. Ideally, these requests should be cached by DNS resolver installed on the server.

Is there some special requirements or config to take care of? My system always reports "Failed to get host data"

**Comment by liuch** [comment]
> Is there some special requirements or config to take care of? My system always reports "Failed to get host data"

No, there are no any special requirements and options you need to customize. This error occurs when there is a problem with a database query. Could you please provide more details about this bug? You can see the details in your browser console if you have the $debug = 1 option set, or in your server logs.

**Comment by liuch** [comment]
> What I don't like about this approach is that without action (click) you still see only a possibly long list of ip-addresses without information. I would have to click maybe hundreds of server entries in the summary report to find one entry that is out of line.

I'm going to refine the web interface in that direction. I am going to add an option where you can specify what you want to see instead of the IP address in the report view dialog. The button is only part of the solution.

> I think that the only correct way of doing this is to get the information (iprev check and domain name) while processing new dmarc summary reports server side and store it in a server table. Then group the entries based on a part of the domain name to an alias name for a provider.

I don't think it's a good idea to automatically make heavy DNS queries based on an external report. There may be many records with different IP addresses in the report. Not all mail server administrators set up local DNS resolvers and many such queries will not only slow down the php script (there is a runtime limit), but may also cause temporary blocking by an external DNS resolver, which will negatively affect on the basic functionality of the mail server. I had a similar experience when setting up a spam filter.

As for the table in the database - I agree with you, it is necessary. The thing is, I also need to make other changes to the database structure for other functionality and I want to make those changes in one go.

**Comment by KlaasBonnema** [comment]
> > I think that the only correct way of doing this is to get the information (iprev check and domain name) while processing new dmarc summary reports server side and store it in a server table. Then group the entries based on a part of the domain name to an alias name for a provider.
> 
> I don't think it's a good idea to automatically make heavy DNS queries based on an external report. There may be many records with different IP addresses in the report. Not all mail server administrators set up local DNS resolvers and many such queries will not only slow down the php script (there is a runtime limit), but may also cause temporary blocking by an external DNS resolver, which will negatively affect on the basic functionality of the mail server. I had a similar experience when setting up a spam filter.
> 
> As for the table in the database - I agree with you, it is necessary. The thing is, I also need to make other changes to the database structure for other functionality and I want to make those changes in one go.

Well, since the DNS queries are going to be made server side anyway, you may as well take the hit once when you are processing the records. You will be able to look up previous reports with the same ip-address that you found before and avoid a dns query.
A DNS query is not so much heavy and usually it is very fast but it can take up to 4 seconds to respond. You can extend the script timeout to make sure you don't run into a timeout. Who cares that processing the new dmarc reports takes 20 seconds or 10 minutes.

Actually, the way my installation is doing it, the iprev checks are initiated by javascript when the page is loaded. The (summary report) page may have a hundred ip-addresses to resolve. Javascript just fires them asynchronously to the server where each request is processed by a PHP script. The response is sent back and dynamically refreshes the text for only that specific ip-address. Usually this is finished in just a few seconds, sometimes you can see them being updated in bunches with one or two seconds apart.
The difference with doing it while processing the dmarc reports is that it happens multithread instead of sequential. The load on the server is eventually the same and the load on the dns servers is identical. I don't feel sorry for the dns servers. This is exactly why they are there. If I were a dns resolver I would prefer to take the hits sequentially rather than multi-threaded.

**Comment by liuch** [comment]
> You can extend the script timeout to make sure you don't run into a timeout. Who cares that processing the new dmarc reports takes 20 seconds or 10 minutes.

Not everyone can extend the script timeout. Shared hosting users usually can't.

> The difference with doing it while processing the dmarc reports is that it happens multithread instead of sequential. The load on the server is eventually the same and the load on the dns servers is identical.

That's not entirely true. At least in the case of Apache HTTP server, which creates a separate process to process each request, which greatly affects performance and resource consumption. Although I haven't used Apache for a long time, maybe something has changed since then.

In any case, I'm still working on improving this feature.

**Comment by ReVoLt112** [comment]
> > Is there some special requirements or config to take care of? My system always reports "Failed to get host data"
> 
> No, there are no any special requirements and options you need to customize. This error occurs when there is a problem with a database query. Could you please provide more details about this bug? You can see the details in your browser console if you have the $debug = 1 option set, or in your server logs.

Error content: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dmarc.reports' doesn't exist in /usr/share/nginx/html/classes/Database/Mariadb/HostMapper.php:85
Stack trace:
#0 /usr/share/nginx/html/classes/Database/Mariadb/HostMapper.php(85): PDOStatement->execute()
#1 /usr/share/nginx/html/classes/Hosts/Host.php(180): Liuch\DmarcSrg\Database\Mariadb\HostMapper->statistics()
#2 /usr/share/nginx/html/classes/Hosts/Host.php(97): Liuch\DmarcSrg\Hosts\Host->statistics()
#3 /usr/share/nginx/html/public/hosts.php(75): Liuch\DmarcSrg\Hosts\Host->information()
#4 {main} common.js:184:12

**Comment by liuch** [comment]
Thank you! Fixed with 35b18d0bf32144a9a7e026e5ff571f7f433afe6c

**Comment by liuch** [comment]
I'm particularly inattentive today. Sorry. Fixed with 984cb705c87e629935cc9888cfba74a11502a822
